### ISSUE TITLE
Compile Error

### ISSUE THREAD

**Issue by senoird** [danielfppps/hydrobuddy#1]
Got it complied but when it starts up says database files are missing choose install dir. After clicking on dir with executable in it ,it just crashes. The only .dbf files I see in source are window and linux.

**Comment by danielfppps** [comment]
The Linux database files should work for both Linux and MacOS. If you're on MacOS after you build the program do not attempt to run it through Lazarus but simply close it and run the application directly. You should then be able to select the application folder and find the dbf files.

**Comment by senoird** [comment]
Maybe im not using lazarus right. Here are my steps. With lazarus open
Project/Open Project then I choose the hydrobuddy.lpi file in the unzipped
hydrobuddy-master folder. In lazarus under Run I choose build. It builds
and in hydrobuddy-master there is an application type file hydrobuddy.
Double click that file hydrobuddy starts but with dialog box "Database
files not found, please select HydroBuddy's installation folder." I choose
the hydrobuddy-master folder where the application file that started
hydrobuddy with resides. At that point i get another dialog box "Open: file
not
found:"/Users/dean/Downloads/hydrobuddy-master/hydrobuddy.app/Contents/MacOS/waterquality_unix.dbf".
Then on hitting OK program closes. There is no folders created at all when
I build the program so Im thinking Im not building it correctly. Any help
would be greatly appreciated.

**Comment by danielfppps** [comment]
In a Mac you need to copy internal files used by an application within your application's folder (this is really what appears to be the application, in reality it's a folder containing application files). Just open up a terminal and issue this command "cp /Users/dean/Downloads/hydrobuddy-master/*.dbf /Users/dean/Downloads/hydrobuddy-master/hydrobuddy.app/Contents/MacOS/". The program should then work.

**Comment by senoird** [comment]
Thanks that worked. Im still getting used to Mac I guess, because I was
looking for a folder being created called hydrobuddy.app. Then I found the
"Show Package Contents" in the right click menu of the application file
which is where all the rest of the folders and files exists. Thanks for
your help greatly appreciated.
