### ISSUE TITLE
Order of elements in element overview in CSV file is not consistent with “main screen” and/or industry standards.

### ISSUE THREAD

**Issue by WO15** [danielfppps/hydrobuddy#3]
In the CSV file containing the result overview, in the “element overview section” NH4+ is listed at the bottom, probably more clear to use the standard ranking as also used on the "Main page" in Hydrobuddy. So move NH4+ just under NO3-, switch P and K and place the trace elements in the same order. This makes comparing previous exported results with new/improved recipes in Hydrobuddy easier, also it is easier to compare Hydrobuddy results with standard fertilizer reports of commercial fertilizer mixes.

Hydrobuddy 1.62 on Linux

**Comment by danielfppps** [comment]
Order of elements has been corrected in v1.96.
