### ISSUE TITLE
The weight percentage of Ca in Calcium Carbonate CaCO3 seems not to be correct.

### ISSUE THREAD

**Issue by WO15** [danielfppps/hydrobuddy#4]
In Hydrobuddy. 1.62 for Linux.
You see under substance selection, for Calcium Carbonate CaCO3 an Ca weight percentage of 11.999% is listed. This seems not correct. 
According to http://www.webqc.org/molecular-weight-of-CaCO3.html the Ca mass percentage is 40.0432%.

**Comment by danielfppps** [comment]
Thanks for reporting. Fixed in latest commit.
