### ISSUE TITLE
Unit of measurement for the rows in substances_used_unix.dbf

### ISSUE THREAD

**Issue by tappoz** [danielfppps/hydrobuddy#6]
Is the unit of measurement for the rows in `substances_used_unix.dbf` PPM? (Parts Per Million)
I can see that in `formulations_unix.dbf` there is a column stating `PPM`, so am I right in assuming that the substances follow the same rule?

**Comment by danielfppps** [comment]
The substance databases contain composition information for substances as displayed in the substance selection menu when you edit substances. These values are therefore in percent, not in ppm.

**Comment by tappoz** [comment]
Oh, I see. But then I would expect those elements specified in a substance would add up to 100%. 

Take for example Ammonium Chloride: clicking on the "Edit Values" button then I see the list of all the elements, most of them set to 0 percentage. 

- There's N (NH4+) that is at 26.192 percentage 
- and Cl at 66.272 percentage. 

If I add together them then I get 92.464, why is this not 100?
Also these numbers are percentage of what? What's the unit of measurement of which they are a percentage?

**Comment by danielfppps** [comment]
The percentages do not necessarily add to 100% because HydroBuddy does not track the percent composition of every element. In the example you suggest 26.192% is N, 66.272% is Cl and the remaining is H, which is not tracked by the software. The NH4+ denomination next to the N tracks that the N comes from NH4+, as this is important from a biological perspective.

The percent values are percent of total weight (w/w %).

**Comment by tappoz** [comment]
Thanks about that - it makes sense. Regarding PPM formulations: are these defaults to 1 milligram / liter, or 1 milligram / kilogram, or 1 gram / 1 cubic meter?

**Comment by danielfppps** [comment]
They are in mg/L or g/m3 (these two are the same)

**Comment by tappoz** [comment]
Thank you. I am also trying to figure out how is the EC calculated. On the main `hb_main.pas` I see an array with 16 elements like `ec_contribution[0]  := 71.46 / 14;`. What is that fraction? How are defined the numerator and denominator? What units of measurement?

**Comment by danielfppps** [comment]
Those are the limiting molar conductivity values for the ions divided by the molar mass of each element (to get the molar concentration of the ions). You can read more about how EC is calculated in HydroBuddy in this post https://scienceinhydroponics.com/2020/04/nutrient-solution-conductivity-estimates-in-hydrobuddy.html
