### ISSUE TITLE
Access Violation Error

### ISSUE THREAD

**Issue by cozy1** [danielfppps/hydrobuddy#9]
HB Version 1.95 throws an "Access violation" error when the "Carry Out Calculation"  button is pressed and "Concentrations from Weights" radio button is active. 

![Error](https://user-images.githubusercontent.com/6805057/128084608-0a5198d1-97a8-46b0-87d4-ef2843109795.JPG)

To reproduce this error:
1) Press "Substance Selection", select Calcium Nitrate,  Set Amount to 2.4 grams, return to main screen
2) Change Volume to 1, Units to Gallons
3) Select "Concentrations from Weights", and press "Carry Out Calculations" button.
4) "Access violation" error is thrown.

x64 PC, Win7,  Win10 

The error may be here in all_element_contributions[j][i-1]: https://github.com/danielfppps/hydrobuddy/blob/6704acfcb72a572b496fbfbe7fefdcd780c144ea/hb_main.pas#L2952

**Comment by cozy1** [comment]
My fork of HydroBuddy with the error fix can be found [here](https://github.com/cozy1/hydrobuddy)

An optimized release build for Windows PCs is [here](https://github.com/cozy1/hydrobuddy/releases/tag/1.9.5.1)

**Comment by danielfppps** [comment]
Thanks for reporting this and for contributing with a forked release with a fix. However, I see your release just handled the error, instead of fixing the cause. I will be releasing v1.96 in the next couple of days with the root cause of the issue fixed.
